### ISSUE TITLE
License in contrib/fping.spec is not accurate

### ISSUE THREAD

**Issue by ulm** [schweikert/fping#192]
Forwarding downstream [Gentoo bug 653356](https://bugs.gentoo.org/653356#c3):

The package is released under a very old variant of the BSD license that was used with 4.3BSD-Tahoe in 1988. See for example:
https://fedoraproject.org/wiki/Licensing:BSD#BSD_Three_Clause_Variant
https://en.wikipedia.org/wiki/BSD_licenses#Previous_license

This is neither identical to BSD-4 nor to the 3-clause "new" BSD license (even if Fedora has confusingly named it so). Commit db7b97cd has changed the license tag in fping.spec from "MIT" to "BSD with advertising", which IMHO doesn't accurately describe the actual license of the package.

Also, the license doesn't grant the right to distribute modified versions (freedom 3), so technically it is not a free software license.

**Comment by schweikert** [comment]
Regarding fping.spec: note that this file is part of "contrib" so not considered to be an official part of fping. I am not sure what should be put there actually. From my point of view, an option is also to remove the .spec file altogether.

Regarding the license itself: the license is old and unchanged since when fping was created, and when that license was in use by other free software. Considering that redistribution of modified version is not explicitely prohibited and also no objection has been raised by anybody since at least the year 2001 when first changes outside of Stanford University were done, I would consider it defact as a granted right. On the other hand, I am not a lawyer...

I asked Stanford University whether relicensing would be an option to clear this once and for all. It would be a shame if we need to stop redistribution and further development of fping.

**Comment by ulm** [comment]
Hm, there doesn't seem to be a standard SPDX label for this license, and Fedora/Redhat don't have a short name for it (although they list the variant on their BSD page, see above). Gentoo uses `fping` as license label. :smile:

> Regarding fping.spec: note that this file is part of "contrib" so not considered to be an official part of fping. I am not sure what should be put in the license tag. From my point of view, an option is also to remove the .spec file altogether.

In any case, that file is distro specific (because the `License` identifiers are).

If you decide to keep it, I'd suggest using `License: Freely redistributable without restriction` for now (see https://fedoraproject.org/wiki/Archive:PackagingDrafts/LicenseTag#.22Distributable.22), until the issue will be sorted out with Stanford.
