### ISSUE TITLE
Inconsistent behavior with -g option

### ISSUE THREAD

**Issue by david-macmahon** [schweikert/fping#267]
`fping` shows the same (alive) host as being both unreachable and alive depending on the CIDR subnet given to the `-g` option.  Here is what I see:

```bash
# fping -v
fping: Version 4.2
fping: comments to david@schweikert.ch

# fping -qug 192.168.32.0/23 | grep 254
192.168.32.254
192.168.33.254

# fping -qag 192.168.33.240/28
192.168.33.241
192.168.33.242
192.168.33.243
192.168.33.244
192.168.33.245
192.168.33.246
192.168.33.247
192.168.33.248
192.168.33.249
192.168.33.250
192.168.33.251
192.168.33.252
192.168.33.253
192.168.33.254
```

Why does `192.168.33.254`, which is definitely alive, appear in the output of both commands?  It should appear in the alive output only and not in the unreachable output.

**Comment by darless** [comment]
Testing against fping 5.1 I don't see this issue, below I have 192.168.1.254 as reachable and 192.168.0.254 as unreachable.
```
docker run fping -v
fping: Version 5.1

# 1.254 is alive
docker run fping 192.168.1.254
192.168.1.254 is alive

$ docker run fping -qug 192.168.1.0/23 | grep 254
192.168.0.254

$ docker run fping -qag 192.168.1.240/28 
192.168.1.254
```

Also tested against 4.2 (using v4.2 tag) also don't see the issue.
```
$ docker run fping:4.2 -v
fping: Version 4.2
fping: comments to david@schweikert.ch
```

```
$ docker run fping:4.2 -qug 192.168.1.0/23 | grep 254
192.168.0.254
docker run fping:4.2 -qag 192.168.1.240/28
192.168.1.254
```

Since I can't reproduce, what does tcpdump show you when you run the command, do you get a response for 192.168.33.254 when you do the /23 mask, since that's testing a lot more addresses at once than /28. Doing a tcpdump for those ranges in testing captured 7k packets for /23 vs 213 packets for /28.

**Comment by auerswal** [comment]
Perhaps the system with IP address 192.168.33.254 uses ICMP rate limiting, or has an unstable connection, or is sometimes overloaded, and thus sometimes appears unreachable, sometimes reachable?

I do not expect this to be an fping issue.
