### ISSUE TITLE
Packaging and distribution of fping for ARM to Raspberry Pi distributions

### ISSUE THREAD

**Issue by vielmetti** [schweikert/fping#81]
The version of `fping` that I got when I installed it on my Raspberry Pi 2 identifies itself as

```
fping: Version 3.2
```

The code for 3.10 seems to compile fine - the question is what the process is by which Raspbian gets updated to the latest version. This issue is probably resolved with some kind of downstream fix, not any change to the code, but honestly I am not sure where to open up that issue elsewhere hence the request here.

**Comment by xtaran** [comment]
Raspbian is based on Debian. If your Raspbian release shipped with fping 3.2, you're running Raspbian based on Debian 7 "Wheezy". The Raspbian release based on Debian 8 "Jessie" already ships fping 3.10. So if you dist-upgrade your whole Raspbian from Wheezy to Jessie, you will get fping 3.10, too.

As far as I know, Raspbian follows Debian quite closely—also with regards to update policies, so I expect there is no other way of getting a newer fping into your Raspbian installation besides compiling it yourself, dist-upgrading your whole installation, reinstalling it with Raspbian based on Debian 8 "Jessie" or [installing Debian 8 "Jessie" directly](https://wiki.debian.org/RaspberryPi2). The latter is possible without performance loss in your case because of the Raspberry Pi 2 having the required instruction set to run the Debian `armhf` architecture without recompiling (which is what Raspbian basically did for the Raspberry Pi 1).

**Comment by schweikert** [comment]
Thanks xtaran for the helpful response!
